### ISSUE TITLE
no game and cant get to my ship

### ISSUE THREAD

**Issue by chanzie** [theFisher86/NMSMasterMod#2]
im new to using mods or pretty new at least and I cant get to my ship in the game I was just in it was stuck behind some texture that was not appearing on screen

**Comment by theFisher86** [comment]
It sounds like you spawned inside a model, this can happen in the first use of the mod. Disable the mod, save in a space station, re enable the mod and everything should be fine.

**Comment by theFisher86** [comment]
By the way: this issue won't occur if you follow the installation steps as described in the readme

**Comment by chanzie** [comment]
thats the problem I did follow the instructions and installed to a **_new world_** fixed it by farming enough mats to summon ship out after fixing ship but then when went to go and get hyperdrive it was covered with the one stone that it takes the land vehicles to remove I couldnt even get in the door of that one so reset world again and kept on having issues with that ore blocking areas over and over when im no where near the part to build yet...

**Comment by theFisher86** [comment]
Go to a different planet.  Unfortunately we can't control which models randomly become converted to detrium and this can occasionally happen.  There's no fix for this without completely removing Megaliths and that is not something I'm willing to do.
